### ISSUE TITLE
Is it possible to merge hOCR HTML into a PDF file?

### ISSUE THREAD

**Issue by tukusejssirs** [hellerbarde/stapler#82]
I’d like to merge hOCR HTML into a PDF file. I thought I could do this using the following command, but it failed (see the output). Is it possible at all?

<details>
  <summary><code>pdf-stapler background pdf_with_images.pdf hocr.html merged.pdf</code></summary>

```bash
Traceback (most recent call last):
  File "/usr/bin/pdf-stapler", line 11, in <module>
    load_entry_point('stapler==1.0.0rc1', 'console_scripts', 'pdf-stapler')()
  File "/usr/lib/python3.8/site-packages/staplelib/__init__.py", line 12, in main
    stapler.main()
  File "/usr/lib/python3.8/site-packages/staplelib/stapler.py", line 116, in main
    modes[mode](args)
  File "/usr/lib/python3.8/site-packages/staplelib/commands.py", line 145, in background
    filesandranges = iohelper.parse_ranges(args[:-1])
  File "/usr/lib/python3.8/site-packages/staplelib/iohelper.py", line 103, in parse_ranges
    "pdf": read_pdf(inputname),
  File "/usr/lib/python3.8/site-packages/staplelib/iohelper.py", line 34, in read_pdf
    pdf = PdfFileReader(open(filename, "rb"))
  File "/usr/lib/python3.8/site-packages/PyPDF2/pdf.py", line 1084, in __init__
    self.read(stream)
  File "/usr/lib/python3.8/site-packages/PyPDF2/pdf.py", line 1696, in read
    raise utils.PdfReadError("EOF marker not found")
PyPDF2.utils.PdfReadError: EOF marker not found
```
</details

Note: I installed `pdf-stapler` v1.0.0 on Fedora 31 from the repos.

**Comment by hellerbarde** [comment]
I don't think there is any support for any non-PDF files by the library we're using here. This is likely out of scope, unless you would like to create a clean pull request for it.
